baseURL: http://example.org/                  # Hosting location.
languageCode: en-us                           # Locale
title: Meghna Acme Corporation                       # Name of the website
theme: Eclectic                               # Eclectic, Universal, Meghna
enableEmoji: true                             # Enable Emoticons
enableGitInfo: true                           # Allow access to Git data
